name: riverpod_paginated_views
description: "A reference example on how to deal with non-trivial (infinite) paginated views"
version: 0.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  collection: ^1.18.0
  connectivity_plus: ^6.1.0
  dio: ^5.4.0
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  fast_immutable_collections: ^10.2.4
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  flutter_use: ^0.0.4
  freezed_annotation: ^2.4.1
  go_router: ^14.3.0
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.9
  intl: ^0.19.0
  json_annotation: ^4.8.1
  package_info_plus: ^8.1.0
  path_provider: ^2.1.2
  riverpod_annotation: ^2.3.3
  shimmer: ^3.0.0
  stack_trace: ^1.11.1
  talker_dio_logger: ^4.4.1
  talker_flutter: ^4.4.1

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.6.8
  drift_dev: ^2.21.0
  flutter_flavorizr: ^2.2.1
  flutter_gen: ^5.3.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  go_router_builder: ^2.4.0
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.2
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
